Numpy(Numerical Python的简称)是python数值计算重要的基础包，
大多数提供科学计算的包都用NumPy的数组作为构建基础

NumPy的部分功能如下：
ndarray，一个具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组
用于对整组数据进行快读运算的标准数学函数
用于读写磁盘数据的工具以及用于操作内存映射文件的工具
线性代数，随机数生成以及傅里叶变换功能
用于集成由C，C++,Fortain等语言编写的代码A C API

对于大部分数据分析应用而言，我最关注的功能主要集中在：
用于数据整理和清理，子集构造和过滤，转换等快速矢量化数组运算
常用数组算法，如排序，唯一化，集合运算等
高效的描述统计和数据聚合摘要运算
用于异构数据集合的合并/连接运算的数据对齐和关系型数据运算
将条件逻辑表述为数组表达式，而不是带有if-elif-else分支循环
数据的分组运算（聚合，转换，函数应用）

NumPy之所以特别重要的原因之一，是因为它可以高效处理大数组的数据，因为:
NumPy是一个连续内存块中存储数据，独立于其他Python 内置对象。Numpy的c语言编写的算法库可以操作内存，而不必进行类型检查或其他前期工作。比起python的内置序列Numpy数组使用内存更少
NumPy可以在整个数组上执行复杂计算而不需要For 循环

In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
# 各个序列分别乘以2
%time for _ in range(10):my_arr2 = my_arr  * 2

CPU times: total: 15.6 ms
Wall time: 23.1 ms


In [3]:
%time for _ in range(10):my_list2 = my_list * 2

CPU times: total: 312 ms
Wall time: 312 ms


Numpy的ndarray 一种多维数组对象
NumPy重要一个特点是其N维数组对象，该对象是一个快速而灵活的大数据集容器

In [4]:
import numpy as np
data = np.random.randn(2,3)
data

array([[ 0.2949905 ,  0.43922286,  0.79395427],
       [-0.8698906 , -1.02752813, -0.25810584]])

In [5]:
data * 10

array([[  2.94990502,   4.39222861,   7.93954273],
       [ -8.69890597, -10.27528126,  -2.58105841]])

In [6]:
data + data

array([[ 0.589981  ,  0.87844572,  1.58790855],
       [-1.73978119, -2.05505625, -0.51621168]])

标准是习惯用法 import numpy as np
你当然也可以代码中使用 from numpy import *，但不建议这么做。
numpy 的命名空间很大，包含许多函数，有一些函数会与python 内置函数重命名

In [7]:
#shape 表示各维度大小元组
#dtype 一个用于说明数组数据类型的对象
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

创建ndarray
使用array函数，它接受一切序列对象包括其他数组，然后产生一个新的含传入数据Numpy 数组

In [10]:
data = [6,5,7,9,10]
narr = np.array(data)
data

[6, 5, 7, 9, 10]

In [11]:
narr

array([ 6,  5,  7,  9, 10])

In [14]:
# 嵌套序列会被转换一个多维数组
data2 = [[1,2,3,4],[5,6,7,8]]
narr2 = np.array(data2)
narr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

np.array可以创建zeros和ones分别可以创建指定长度和形状全0或者全1数组
empty可以创建一个没有任何具体值的数组

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.empty((2,3,4))

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
         1.11260755e-306],
        [1.33511969e-306, 1.42418987e-306, 7.56599807e-307,
         8.90104239e-307],
        [1.24610383e-306, 1.69118108e-306, 8.06632139e-308,
         1.20160711e-306]],

       [[1.69119330e-306, 1.06811151e-306, 8.45609552e-307,
         1.60221072e-306],
        [1.51317924e-306, 1.24610994e-306, 8.34423493e-308,
         8.34424342e-308],
        [1.78021527e-306, 9.79107193e-307, 8.34420522e-308,
         1.42410974e-306]]])

认为np.empty会返回全0数组的想法是不安全的，
很多情况下它返回一些未初始化的垃圾值

In [ ]:
arange是python内置函数的数组版

In [18]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [27]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr1

array([1., 2., 3.])

In [29]:
arr_int = np.array([1,2,3,4],dtype=np.int32)
arr_int

array([1, 2, 3, 4])